spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                defer-datasource-initialization: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
